name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build-installer:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: download bundled tools
        run: pnpm download:modpreview

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseBody: 'See assets below to download and install.'
          releaseDraft: true

  build-portable:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      
      - name: download bundled tools
        run: pnpm download:modpreview

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseBody: 'See assets below to download and install.'
          releaseDraft: true
          args: --no-bundle --features portable
          uploadPlainBinary: true
          assetNamePattern: '[name]-[version]-portable[ext]'